version: '3'
services:
  python3:
    restart: always
    ports:
      - '7777:8888'
    build: .
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/src