version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: "\
        dev.ray-beams.xyz -> http://172.30.0.3:8000,\
        techblog.ray-beams.xyz -> http://172.30.0.3:8001"
      STAGE: ${STAGE}
      # FORCE_RENEW: 'true'
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  nginx:
    image: nginx:1.17-alpine
    ports:
      - '8000:8000'
      - '8001:8001'
    volumes:
      - ./logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../lara6:/var/www/html/lara6
      - ../pj_manager:/var/www/html/pj_manager
      - ../app_memo:/var/www/html/app_memo
    environment:
      - TZ=${TZ}
    networks:
      app_net:
        ipv4_address: 172.30.0.3

  db:
    build:
      context: "."
      dockerfile: ./Dockerfile-mysql
    volumes:
      - db-store:/var/lib/mysql
      - db-log-store:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      # - MYSQL_DATABASE=${DB_NAME}
      # - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    networks:
      app_net:
        ipv4_address: 172.30.0.4

  php:
    build:
      context: "."
      dockerfile: Dockerfile-php
      args:
        - TZ=${TZ}
    volumes:
      - ../lara6:/works/lara6
      - ../pj_manager:/works/pj_manager
      - ../app_memo:/works/app_memo
      - ./logs:/var/log/php
      - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /works
    environment:
      # - DB_CONNECTION=mysql
      # - DB_HOST=db
      # - DB_DATABASE=${DB_NAME}
      # - DB_USERNAME=${DB_USER}
      # - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    networks:
      app_net:
        ipv4_address: 172.30.0.5

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

volumes:
  db-store:
  db-log-store:
